publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  esbuild: true
  netlify-cli: true
  oxc-resolver: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true
  workerd: true
